// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using animalrescue.mainmodule.dal;

#nullable disable

namespace animalrescue.mainmodule.dal.Migrations.SqliteMigrations
{
    [DbContext(typeof(LocalAnimalRescueContext))]
    [Migration("20221027172113_Added_Accounts_Roles")]
    partial class AddedAccountsRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11");

            modelBuilder.Entity("animalrescue.mainmodule.dal.models.AdoptionApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AdoptionApplication");
                });

            modelBuilder.Entity("animalrescue.mainmodule.dal.models.AnimalRescueAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnimalRescueAccount");
                });

            modelBuilder.Entity("animalrescue.mainmodule.dal.models.AnimalRescueAccountRole", b =>
                {
                    b.Property<int>("AnimalRescueAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimalRescueAccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AnimalRescueAccountRole");
                });

            modelBuilder.Entity("animalrescue.mainmodule.dal.models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("animalrescue.mainmodule.dal.models.VolunteerApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VolunteerApplication");
                });

            modelBuilder.Entity("animalrescue.mainmodule.dal.models.AnimalRescueAccountRole", b =>
                {
                    b.HasOne("animalrescue.mainmodule.dal.models.AnimalRescueAccount", "AnimalRescueAccount")
                        .WithMany("AnimalRescueAccountRoles")
                        .HasForeignKey("AnimalRescueAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("animalrescue.mainmodule.dal.models.Role", "Role")
                        .WithMany("AnimalRescueAccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalRescueAccount");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("animalrescue.mainmodule.dal.models.AnimalRescueAccount", b =>
                {
                    b.Navigation("AnimalRescueAccountRoles");
                });

            modelBuilder.Entity("animalrescue.mainmodule.dal.models.Role", b =>
                {
                    b.Navigation("AnimalRescueAccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
