name: Build and Run tests

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Build with dotnet
        run: dotnet build

      - name: Run tests
        run: dotnet test